apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myname
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: nginx
    repoURL: 'git@github.com:amitopenwriteup/argocdproject.git'
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
